"use client";

import { FormEvent, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { addMatchGoalAction, deleteMatchGoalAction } from "@/actions/match.actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { MatchGoalDto, MatchSideDto } from "@/types/match.types";

export function MatchGoalsList({ goals, sides, manageableSideIds, onMinuteClick }: { goals: MatchGoalDto[]; sides: MatchSideDto[]; manageableSideIds: string[]; onMinuteClick?: (minute: number, extraMinute?: number) => void }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const side = sides.find((item) => item.id === values.matchSideId); startTransition(async () => { const result = await addMatchGoalAction({ ...values, matchId: side?.matchId, minute: values.minute || undefined, extraMinute: values.extraMinute || undefined }); setMessage(result.message); if (result.ok) { form.reset(); router.refresh(); } }); }
  function remove(id: string) { startTransition(async () => { const result = await deleteMatchGoalAction(id); setMessage(result.message); if (result.ok) router.refresh(); }); }
  return <div className="grid gap-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Qollar</p><div className="grid gap-4 sm:grid-cols-2">{sides.slice(0, 2).map((side) => <div key={side.id}><p className="mb-1 text-xs font-semibold">{side.name}</p><div className="grid gap-1">{goals.filter((goal) => goal.matchSideId === side.id).map((goal) => <div key={goal.id} className="flex items-center gap-2 text-sm">{goal.minute ? <button type="button" className="w-12 text-left font-medium text-primary hover:underline" title="Dəqiqəyə keç" onClick={() => onMinuteClick?.(goal.minute!, goal.extraMinute ?? 0)}>{goal.minute}{goal.extraMinute ? `+${goal.extraMinute}` : ""}’</button> : <span className="w-12 text-muted-foreground">—</span>}<span className="flex-1 truncate">{goal.playerName}</span>{manageableSideIds.includes(side.id) ? <button type="button" className="text-xs text-muted-foreground hover:text-destructive" disabled={pending} onClick={() => remove(goal.id)}>Sil</button> : null}</div>)}{!goals.some((goal) => goal.matchSideId === side.id) ? <p className="text-xs text-muted-foreground">Qol yoxdur</p> : null}</div></div>)}</div>{manageableSideIds.length ? <form className="grid gap-2 border-t pt-3 sm:grid-cols-[130px_1fr_80px_80px_auto]" onSubmit={submit}><select name="matchSideId" className="h-9 rounded-md border bg-background px-2 text-sm" required>{sides.filter((side) => manageableSideIds.includes(side.id)).map((side) => <option key={side.id} value={side.id}>{side.name}</option>)}</select><Input name="playerName" placeholder="Qol vuran oyunçu" required /><Input name="minute" type="number" min={1} max={150} placeholder="Dəqiqə" /><Input name="extraMinute" type="number" min={0} max={15} placeholder="Əlavə" /><Button size="sm" disabled={pending}>Qol əlavə et</Button></form> : null}{message ? <p className="text-xs text-muted-foreground">{message}</p> : null}</div>;
}
