import { CalendarDays, MapPin } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { MatchGoalsList } from "@/components/matches/match-goals-list";
import type { MatchDto } from "@/types/match.types";

export function MatchSummaryCard({ match, manageableSideIds, actions, onGoalMinuteClick }: { match: MatchDto; manageableSideIds: string[]; actions?: React.ReactNode; onGoalMinuteClick?: (minute: number, extraMinute?: number) => void }) {
  const [first, second] = match.sides;
  return <Card className="overflow-hidden"><CardContent className="grid gap-8 p-6 lg:grid-cols-[minmax(240px,1fr)_minmax(360px,1.4fr)_minmax(220px,0.8fr)] lg:items-center lg:p-8"><div><div className="flex flex-wrap gap-2"><Badge>{match.type.replaceAll("_", " ")}</Badge><Badge variant="secondary">{match.status.replaceAll("_", " ")}</Badge><Badge variant="secondary">{match.category}</Badge></div><h1 className="mt-4 text-2xl font-bold sm:text-3xl">{match.title ?? `${first?.name ?? "Team A"} vs ${second?.name ?? "Team B"}`}</h1><div className="mt-4 grid gap-2 text-sm text-muted-foreground"><p className="flex items-center gap-2"><CalendarDays className="h-4 w-4" />{new Intl.DateTimeFormat("az-AZ", { dateStyle: "full", timeStyle: "short" }).format(new Date(match.startTime))}</p><p className="flex items-center gap-2"><MapPin className="h-4 w-4" />{match.venue ?? "Meydança göstərilməyib"}</p></div></div><div className="rounded-xl bg-secondary/60 p-5 text-center"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-4"><p className="truncate font-semibold">{first?.name ?? "Team A"}</p><p className="text-4xl font-black tracking-tight sm:text-5xl">{match.homeScore ?? "–"} <span className="text-muted-foreground">:</span> {match.awayScore ?? "–"}</p><p className="truncate font-semibold">{second?.name ?? "Team B"}</p></div>{match.resultNote ? <p className="mx-auto mt-3 max-w-lg text-sm text-muted-foreground">{match.resultNote}</p> : null}<div className="mt-5 border-t pt-4 text-left"><MatchGoalsList goals={match.goals} sides={match.sides} manageableSideIds={manageableSideIds} onMinuteClick={onGoalMinuteClick} /></div></div><div className="grid gap-3">{actions ?? <p className="text-sm text-muted-foreground">Oyun əməliyyatları statusa uyğun burada görünəcək.</p>}</div></CardContent></Card>;
}
